
SELECT * FROM tbcliente;

USE sucos;

SELECT * FROM tbcliente;

SELECT CPF, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA FROM tbcliente;

SELECT CPF, NOME FROM tbcliente;

SELECT CPF, NOME FROM tbcliente LIMIT 5;

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM tbcliente;

SELECT CPF, NOME, SEXO, IDADE, DATA_NASCIMENTO FROM tbcliente order by NOME;
SELECT * FROM tbproduto WHERE PRODUTO = '544931';

SELECT * FROM tbcliente WHERE CIDADE = 'RIO DE JANEIRO';

SELECT * FROM tbproduto WHERE SABOR = 'LIMAO';

UPDATE tbproduto SET SABOR = 'Citricos' WHERE SABOR = 'LIMAO';

SELECT * FROM tbproduto WHERE SABOR = 'Citricos';

SELECT * FROM tabela_de_vendedores WHERE NOME = 'CLAUDIA MORAIS';

SELECT * FROM tbcliente WHERE IDADE = 23;

SELECT * FROM tbcliente WHERE IDADE > 23;
SELECT * FROM tbcliente WHERE IDADE < 23;
SELECT * FROM tbcliente WHERE IDADE <= 22;
SELECT * FROM tbcliente WHERE IDADE <> 22;

SELECT * FROM tbcliente WHERE NOME >= 'FERNANDO CAVALCANTE';

SELECT * FROM tbproduto;
SELECT * FROM tbproduto WHERE PRECO_LISTA > 16.008;
SELECT * FROM tbproduto WHERE PRECO_LISTA < 16.008;

SELECT * FROM tbproduto WHERE PRECO_LISTA between 16.007 AND 16.008;